server:
  port: 9095

spring:
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  application:
    name: candidate-app
  datasource:
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:postgres}
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://0.0.0.0:5432/}
    hikari:
      minimum-idle: ${DB_MIN_IDLE:3}
      maximum-pool-size: ${DB_MAX_POOL_SIZE:10}
      idle-timeout: ${DB_IDLE_TIMEOUT:30000}
  flyway:
    locations: classpath:db/migration/postgresql
    user: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:postgres}
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://0.0.0.0:5432/}
    baselineOnMigrate: true
    enabled: true

cors:
  allowed:
    origins: ${CORS_ALLOWED_ORIGINS:http://localhost:5173}
