server:
  port: 9095

spring:
  application:
    name: candidate-app
  datasource:
    url: ${DB_URL:jdbc:h2:file:./candidate-app-db;AUTO_RECONNECT=TRUE;AUTO_SERVER=TRUE}
    driverClassName: ${DB_DRIVER:org.h2.Driver}
    username: ${DB_USERNAME:sa}
    password: ${DB_PASSWORD:}
    hikari:
      minimum-idle: ${DB_MIN_IDLE:3}
      maximum-pool-size: ${DB_MAX_POOL_SIZE:10}
      idle-timeout: ${DB_IDLE_TIMEOUT:30000}
  jpa:
    database-platform: ${DB_DIALECT:org.hibernate.dialect.H2Dialect}
    hibernate:
      ddl-auto: none
  flyway:
    locations: classpath:db/migration/{vendor}
    url: ${DB_URL:jdbc:h2:file:./candidate-app-db;AUTO_RECONNECT=TRUE;AUTO_SERVER=TRUE}
    user: ${DB_USERNAME:sa}
    password: ${DB_PASSWORD:}
    schemas: ${DB_SCHEMA:}
    baselineOnMigrate: true
    enabled: true

jpa:
  show:
    sql: ${JPA_SHOW_SQL:false}
