server:
  port: 9095

spring:
  application:
    name: candidate-app
  datasource:
    username: postgres
    password: postgres
    url: jdbc:postgresql://0.0.0.0:5432/
    hikari:
      minimum-idle: ${DB_MIN_IDLE:3}
      maximum-pool-size: ${DB_MAX_POOL_SIZE:10}
      idle-timeout: ${DB_IDLE_TIMEOUT:30000}
  flyway:
    locations: classpath:db/migration/postgresql
    url: jdbc:postgresql://0.0.0.0:5432/
    user: postgres
    password: postgres
    baselineOnMigrate: true
    enabled: true
